# Generated by Django 4.1.7 on 2023-05-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MriApi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="linecse",
            new_name="licence",
        ),
    ]
